services: 

  challenge: 
    image: docker.io/loftorbital/devsecops-junior-challenge-go:latest
    pull_policy: always
    restart: always
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: "challenge"
      POSTGRES_DB: "challenge"
      POSTGRES_HOST: "postgres"
      TLS_CERT_FILE: /etc/ssl/certs/cert.pem
      TLS_KEY_FILE: /etc/ssl/private/key.pem
    volumes:
      - ../../certs/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ../../certs/key.pem:/etc/ssl/private/key.pem:ro
    ports: 
      - "10000:10000"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:18.0-trixie
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: "challenge"
      POSTGRES_DB: "challenge"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challenge"]
      interval: 5s
