name: Build, Run, Test App and Scan

on:
  push:
    branches: [ "workspace" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-run-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Add Secrets
        run: |
          mkdir ./certs && \
          echo ${{ secrets.CERT_PEM_BASE64 }} | base64 -d > ./certs/cert.pem && \
          echo ${{ secrets.KEY_PEM_BASE64 }} | base64 -d > ./certs/key.pem && \
          echo ${{ secrets.ENV_FILE_BASE64 }} | base64 -d > .env

      - name: Build App and Container
        run: make build

      - name: Start Container
        run: make docker-up

      - name: Run Tests
        run: make test

      - name: Stop Container
        run: make docker-down

  build-scan:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Run SAST Scan
        uses: securego/gosec@master
        with:
          args: -exclude=G104 ./...

      - name: Run SCA Scan
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...

      - name: Add Secrets
        run: |
          mkdir ./certs && \
          echo ${{ secrets.CERT_PEM_BASE64 }} | base64 -d > ./certs/cert.pem && \
          echo ${{ secrets.KEY_PEM_BASE64 }} | base64 -d > ./certs/key.pem && \
          echo ${{ secrets.ENV_FILE_BASE64 }} | base64 -d > .env

      - name: Build App and Container
        run: make build

      - name: Run Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-junior-challenge-go:local'
          severity: 'CRITICAL,HIGH'
