name: Build and Run

on:
  push:
    branches: [ "workspace" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Build App and Container
        run: make build

      - name: Start Container
        run: make docker-up

      - name: Run Tests
        run: make test

      - name: Stop Container
        run: make docker-down
